[build-system]
requires = [
    "setuptools>=42",
    "wheel",
    "joblib==1.0.1",
    "numpy==1.20.3",
    "pandas==1.2.4",
    "pyentrp==0.6.0",
    "python-dateutil==2.8.1",
    "pytz==2021.1",
    "scikit-learn==0.24.2",
    "scipy==1.6.3",
    "six==1.16.0",
    "sklearn==0.0",
    "threadpoolctl==2.1.0",
]
build-backend = "setuptools.build_meta"